language: node_js
node_js:
- '8.11.1'
branchs:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_684ac9f60d62_key -iv $encrypted_684ac9f60d62_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- git config --global user.name niuDazhuang
- git config --global user.email dengwm666@icloud.com
- sed -i'' "s~git@github.com:${GH_HOME}~https://${GH_TOKEN}:x-oauth-basic@github.com/${GH_HOME}~" _config.yml
- cat _config.yml
install:
- npm i
script:
- chmod 600 ~/.ssh/id_rsa
- hexo g -d
- mv public blog && tar zcvf blog.tar.gz blog
addons:
  ssh_known_hosts:
  - 101.132.193.88
after_success:
- scp blog.tar.gz root@101.132.193.88:/www
- ssh root@101.132.193.88 -o StrictHostKeyChecking=no 'cd /www && tar zxvf blog.tar.gz'
env:
  global:
    GH_HOME: niuDazhuang/niudazhuang.github.io.git
